version: '3.8'
services:
  library-db:
    image: postgres:13.3
    container_name: library-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"